In [1]:
import os
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import time

In [2]:
os.chdir('G:/My Drive/2021/Bias/')

test_matrice_reverse = pd.read_csv('test_matrice_reverse.csv', header=None).to_numpy()
#Zero_index = pd.read_csv('Zero_index.csv', header=None).to_numpy()

In [59]:
index_lst = []
with open('user_tsinfo.txt') as f:
    index_lst.append(f.readlines())

time_loc_index = index_lst[0][0]
user_index = index_lst[0][1]

time_loc_index = time_loc_index.split(',')
user_index = user_index.split(',')[:-1]

In [66]:
#time_loc_index
#time, location order
#check location0., 55.,  0.,  0.,  0.,  0.])
obsbyct = np.split(np.sum(np.split(test_matrice_reverse[:, 1:].flatten(), 
                         7767*12), 
                axis=1), 7767)


#by one hour
obsbytime = np.split(np.sum(np.split(test_matrice_reverse[:, 1:].flatten(),
                         7767*12*24), 
                axis=1), 
                7767*12)

timesum = []
for i in range(7767):
    timesum.append(np.sum(obsbytime[(12*i):(12*(i+1))], axis=0))
    
obsbytime = np.array(timesum)

In [105]:
obsbyct = pd.DataFrame(obsbyct, columns = list(range(1, 13)))
obsbytime = pd.DataFrame(obsbytime, columns=list(range(1, 25)))

In [74]:
obsbyct.describe()

,1,2,3,4,5,6,7,8,9,10,11,12
count,7767.000000,7767.000000,7767.000000,7767.000000,7767.000000,7767.000000,7767.000000,7767.000000,7767.000000,7767.000000,7767.000000,7767.000000
mean,1.702073,4.081241,4.464143,0.707995,0.701944,1.210892,0.978499,6.248487,2.701429,1.308227,1.316853,2.198275
std,8.966491,15.673365,15.016078,10.866417,7.075118,7.038986,6.306628,17.671387,12.222530,8.168110,8.986134,10.782856
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000
max,187.000000,724.000000,356.000000,738.000000,241.000000,201.000000,179.000000,334.000000,447.000000,342.000000,461.000000,279.000000